const books = [
  {
    image: "./image/book1.jpg",
    author: "John Green",
    pages: "320",
    genre: "Young Adult",
    title: "The Fault in Our Stars",
  },
  {
    image: "image/book2.jpg",
    author: "J.K. Rowling",
    pages: "607",
    genre: "Fantasy",
    title: "Harry Potter and the Sorcerer's Stone",
  },
  {
    image: "image/book3.jpg",
    author: "Jane Austen",
    pages: "279",
    genre: "Romance",
    title: "Pride and Prejudice",
  },
  {
    image: "image/book4.jpg",
    author: "Harper Lee",
    pages: "323",
    genre: "Classic",
    title: "To Kill a Mockingbird",
  },
  {
    image: "image/book5.jpg",
    author: "George Orwell",
    pages: "328",
    genre: "Dystopian",
    title: "1984",
  },
  {
    image: "image/book6.jpg",
    author: "Stephen King",
    pages: "1138",
    genre: "Horror",
    title: "The Stand",
  },
  {
    image: "image/book7.jpg",
    author: "Agatha Christie",
    pages: "256",
    genre: "Mystery",
    title: "Murder on the Orient Express",
  },
  {
    image: "image/book8.jpg",
    author: "Ernest Hemingway",
    pages: "127",
    genre: "Fiction",
    title: "The Old Man and the Sea",
  },
  {
    image: "image/book9.jpg",
    author: "Toni Morrison",
    pages: "324",
    genre: "Literary Fiction",
    title: "Beloved",
  },
  {
    image: "image/book10.jpg",
    author: "Gabriel Garcia Marquez",
    pages: "368",
    genre: "Magical Realism",
    title: "One Hundred Years of Solitude",
  },
  {
    image: "image/book11.jpg",
    author: "J.R.R. Tolkien",
    pages: "1178",
    genre: "Fantasy",
    title: "The Lord of the Rings",
  },
  {
    image: "image/book12.jpg",
    author: "Virginia Woolf",
    pages: "194",
    genre: "Modernist",
    title: "Mrs. Dalloway",
  },
  {
    image: "image/book13.jpg",
    author: "F. Scott Fitzgerald",
    pages: "180",
    genre: "Classic",
    title: "The Great Gatsby",
  },
  {
    image: "image/book14.jpg",
    author: "Margaret Atwood",
    pages: "311",
    genre: "Dystopian",
    title: "The Handmaid's Tale",
  },
  {
    image: "image/book15.jpg",
    author: "Leo Tolstoy",
    pages: "1225",
    genre: "Historical Fiction",
    title: "War and Peace",
  },
  {
    image: "image/book16.jpg",
    author: "Herman Melville",
    pages: "635",
    genre: "Adventure",
    title: "Moby-Dick",
  },
  {
    image: "image/book17.jpg",
    author: "Khaled Hosseini",
    pages: "372",
    genre: "Contemporary",
    title: "The Kite Runner",
  },
  {
    image: "image/book18.jpg",
    author: "Charles Dickens",
    pages: "496",
    genre: "Classic",
    title: "A Tale of Two Cities",
  },
  {
    image: "image/book19.jpg",
    author: "Dan Brown",
    pages: "481",
    genre: "Thriller",
    title: "The Da Vinci Code",
  },
  {
    image: "image/book20.jpg",
    author: "J.D. Salinger",
    pages: "277",
    genre: "Coming-of-Age",
    title: "The Catcher in the Rye",
  },
];
